
export const SCHOLARS_DATA = [
    {
        id: 101,
        name: "ابن عثيمين",
        slug: "uthaymeen",
        img: "https://static.surah.com/images/scholars/uthaymeen.jpg",
        style: "شروحات ودروس",
        description: "العلامة محمد بن صالح العثيمين، من كبار علماء العصر، تميز بأسلوبه العلمي الرصين وشروحاته الماتعة.",
        lectures: [
            { id: 1, title: "شرح رياض الصالحين - المقدمة", url: "https://archive.org/download/SharhRiyadAl-salihin-Uthaymeen/001.mp3" },
            { id: 2, title: "شرح رياض الصالحين - باب الإخلاص", url: "https://archive.org/download/SharhRiyadAl-salihin-Uthaymeen/002.mp3" },
            { id: 3, title: "شرح رياض الصالحين - باب التوبة", url: "https://archive.org/download/SharhRiyadAl-salihin-Uthaymeen/003.mp3" },
            { id: 4, title: "شرح الأربعين النووية - الحديث الأول", url: "https://archive.org/download/SharhAl-arbainAn-nawawiyah-Uthaymeen/01.mp3" },
            { id: 5, title: "شرح عقيدة أهل السنة والجماعة - 1", url: "https://archive.org/download/SharhAqidahAhlAs-sunnahWal-jamaah-Uthaymeen/01.mp3" },
        ]
    },
    {
        id: 102,
        name: "ابن باز",
        slug: "binbaz",
        img: "https://upload.wikimedia.org/wikipedia/en/f/f8/Abdulaziz_ibn_Abdullah_Al_Baz.png",
        style: "فتاوى ودروس",
        description: "سماحة الشيخ عبد العزيز بن باز، مفتي عام المملكة العربية السعودية سابقاً، إمام أهل السنة في عصره.",
        lectures: [
            // Nur Ala Darb Series (Extracted from alaslam2017.blogspot.com)
            { id: 1001, title: "نور على الدرب - الشريط 1", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0001.mp3" },
            { id: 1002, title: "نور على الدرب - الشريط 2", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0002.mp3" },
            { id: 1003, title: "نور على الدرب - الشريط 3", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0003.mp3" },
            { id: 1004, title: "نور على الدرب - الشريط 4", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0004.mp3" },
            { id: 1005, title: "نور على الدرب - الشريط 5", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0005.mp3" },
            { id: 1006, title: "نور على الدرب - الشريط 6", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0006.mp3" },
            { id: 1007, title: "نور على الدرب - الشريط 7", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0007.mp3" },
            { id: 1008, title: "نور على الدرب - الشريط 8", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0008.mp3" },
            { id: 1009, title: "نور على الدرب - الشريط 9", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0009.mp3" },
            { id: 1010, title: "نور على الدرب - الشريط 10", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0010.mp3" },
            { id: 1011, title: "نور على الدرب - الشريط 11", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0011.mp3" },
            { id: 1012, title: "نور على الدرب - الشريط 12", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0012.mp3" },
            { id: 1013, title: "نور على الدرب - الشريط 13", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0013.mp3" },
            { id: 1014, title: "نور على الدرب - الشريط 14", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0014.mp3" },
            { id: 1015, title: "نور على الدرب - الشريط 15", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0015.mp3" },
            { id: 1016, title: "نور على الدرب - الشريط 16", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0016.mp3" },
            { id: 1017, title: "نور على الدرب - الشريط 17", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0017.mp3" },
            { id: 1018, title: "نور على الدرب - الشريط 18", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0018.mp3" },
            { id: 1019, title: "نور على الدرب - الشريط 19", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0019.mp3" },
            { id: 1020, title: "نور على الدرب - الشريط 20", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0020.mp3" },
            { id: 1021, title: "نور على الدرب - الشريط 21", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0021.mp3" },
            { id: 1022, title: "نور على الدرب - الشريط 22", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0022.mp3" },
            { id: 1023, title: "نور على الدرب - الشريط 23", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0023.mp3" },
            { id: 1024, title: "نور على الدرب - الشريط 24", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0024.mp3" },
            { id: 1025, title: "نور على الدرب - الشريط 25", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0025.mp3" },
            { id: 1026, title: "نور على الدرب - الشريط 26", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0026.mp3" },
            { id: 1027, title: "نور على الدرب - الشريط 27", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0027.mp3" },
            { id: 1028, title: "نور على الدرب - الشريط 28", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0028.mp3" },
            { id: 1029, title: "نور على الدرب - الشريط 29", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0029.mp3" },
            { id: 1030, title: "نور على الدرب - الشريط 30", url: "https://archive.org/download/raj3elsada-nor3laAdrb/0030.mp3" },

            // Lessons after Fajr and Maghrib (1404-1405 AH)
            { id: 2001, title: "دروس الفجر والمغرب - الشريط 1", url: "https://archive.org/download/IbnBazDoroos1-25/1.mp3" },
            { id: 2002, title: "دروس الفجر والمغرب - الشريط 2", url: "https://archive.org/download/IbnBazDoroos1-25/2.mp3" },
            { id: 2003, title: "دروس الفجر والمغرب - الشريط 3", url: "https://archive.org/download/IbnBazDoroos1-25/3.mp3" },
            { id: 2004, title: "دروس الفجر والمغرب - الشريط 4", url: "https://archive.org/download/IbnBazDoroos1-25/4.mp3" },
            { id: 2005, title: "دروس الفجر والمغرب - الشريط 5", url: "https://archive.org/download/IbnBazDoroos1-25/5.mp3" },
            { id: 2006, title: "دروس الفجر والمغرب - الشريط 6", url: "https://archive.org/download/IbnBazDoroos1-25/6.mp3" },
            { id: 2007, title: "دروس الفجر والمغرب - الشريط 7", url: "https://archive.org/download/IbnBazDoroos1-25/7.mp3" },
            { id: 2008, title: "دروس الفجر والمغرب - الشريط 8", url: "https://archive.org/download/IbnBazDoroos1-25/8.mp3" },
            { id: 2009, title: "دروس الفجر والمغرب - الشريط 9", url: "https://archive.org/download/IbnBazDoroos1-25/9.mp3" },
            { id: 2010, title: "دروس الفجر والمغرب - الشريط 10", url: "https://archive.org/download/IbnBazDoroos1-25/10.mp3" },
        ]
    },
    {
        id: 103,
        name: "الألباني",
        slug: "albani",
        img: "https://static.surah.com/images/scholars/albani.jpg",
        style: "حديث وسنة",
        description: "المحدث محمد ناصر الدين الألباني، مجدد العصر في علم الحديث، صاحب السلسلة الصحيحة والضعيفة.",
        lectures: [
            { id: 1, title: "سلسلة الهدى والنور - الشريط 1", url: "https://archive.org/download/SilsilatAl-hudaWan-nur-Albani/001.mp3" },
            { id: 2, title: "سلسلة الهدى والنور - الشريط 2", url: "https://archive.org/download/SilsilatAl-hudaWan-nur-Albani/002.mp3" },
            { id: 3, title: "صفة صلاة النبي ﷺ - 1", url: "https://archive.org/download/SifatSalatAn-nabi-Albani/01.mp3" },
            { id: 4, title: "التوحيد أولاً", url: "https://archive.org/download/Albani-Lectures/TawhidFirst.mp3" },
        ]
    }
];
